### ISSUE TITLE
gitea-webhook fails to load config.yaml 

### ISSUE THREAD

**Issue by tchellomello** [zhiminwen/gitea-webhook-tekton#1]
Thanks for this great project @zhiminwen!

With the current contents of `config.yaml`, the `gitea-webook` binary fails to load all the fields expected to process the webook. 

Current:
```yaml
hooks:
  - repo: wenzm/hello-springboot
    secret: secretkey
    taskinfo:
      namespace: demo
      task: my-appsody-build
      gitResourceName: hello-springboot-git-source
      imageResourceName: hello-springboot-registry-image
``` 

Looking at the logs, we can see that some fields failed:

```
Will tail 1 logs...
gitea-webhook-tekton-6f449dd97d-xtrsg
[gitea-webhook-tekton-6f449dd97d-xtrsg] 2019/10/08 15:36:53 main.Config{Hooks:[]main.HookAction{main.HookAction{Secret:"secretkey", Repo:"mmello/unifi-docker", TaskInfo:main.TaskToRun{Namespace:"default", ServiceAccount:"", TaskRefName:"", GitSourceResourceName:"", DockerImageResourceName:""}}}} 
[gitea-webhook-tekton-6f449dd97d-xtrsg] 2019/10/08 15:37:41 repo=mmello/unifi-docker,payload repo=mmello/unifi-docker, secret=secretkey, payload secret=secret1235

.....
 
[gitea-webhook-tekton-6f449dd97d-xtrsg] 2019/10/08 15:52:49 repo=mmello/unifi-docker,payload repo=mmello/unifi-docker, secret=secretkey, payload secret=secret1235 
[gitea-webhook-tekton-6f449dd97d-xtrsg] 2019/10/08 15:52:49 exec command for repo:mmello/unifi-docker 
[gitea-webhook-tekton-6f449dd97d-xtrsg] 2019/10/08 15:52:49 Failed to create TaskRun:admission webhook "webhook.tekton.dev" denied the request: mutation failed: missing field(s): spec.taskref.name, spec.taskspec
``` 

If we look at the code  https://github.com/zhiminwen/gitea-webhook-tekton/blob/master/webhook.go#L15-L21, the contents should be:

```yaml
hooks:
  - repo: mmello/unifi-docker
    secret: secret1235
    taskinfo:
      namespace: default 
      taskrefname: source-to-image
      gitsourceresourcename: unifi-docker-git
      dockerimageresourcename: unifi-internal-registry-image-url
``` 

Then testing the new yaml, we have the following:

```
gitea-webhook-tekton-6654ddb8c8-5qx24
[gitea-webhook-tekton-6654ddb8c8-5qx24] 2019/10/08 19:30:36 main.Config{Hooks:[]main.HookAction{main.HookAction{Secret:"secret1235", Repo:"mmello/unifi-docker", TaskInfo:main.TaskToRun{Namespace:"default", ServiceAccount:"", TaskRefName:"source-to-image", GitSourceResourceName:"unifi-docker-git", DockerImageResourceName:"unifi-internal-registry-image-url"}}}} 
[gitea-webhook-tekton-6654ddb8c8-5qx24] 2019/10/08 19:31:00 repo=mmello/unifi-docker,payload repo=mmello/unifi-docker, secret=secret1235, payload secret=secret1235 
[gitea-webhook-tekton-6654ddb8c8-5qx24] 2019/10/08 19:31:00 exec command for repo:mmello/unifi-docker 
```
